---
- name: configure mongodb replication key
  template:
    src: "mongod.key.j2"
    dest: "{{ mongodb_replSet_keyFile }}"
    owner: "{{ mongodb_daemon_user }}"
    group: "{{ mongodb_daemon_group }}"
    mode: "0600"
  when: mongodb_replSet_key != ""
  notify: mongodb restart

- name: configure mongodb daemon
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - src: mongod.conf.j2
      dest: "{{ mongodb_conf_file }}"
    - src: mongod.service.j2
      dest: "{{ mongodb_daemon_serviceFile }}"
  notify:
    - systemd reload
    - mongodb restart

- meta: flush_handlers

- name: ensure mongodb is started and enabled
  service:
    name: mongod
    state: started
    enabled: true

