---
- block:
  - name: initiate replica set (authenticated)
    community.mongodb.mongodb_replicaset:
      replica_set: "{{ mongodb_replSet_name }}"
      login_host: "127.0.0.1"
      login_port: "27017"
      login_user: "{{ mongodb_admin_user }}"
      login_password: "{{ mongodb_admin_password }}"
      members:
      - localhost:2223
      - localhost:2224
      validate: no

  #- block:
  #- name: connect to master (authenticated)
  #  community.mongodb.mongodb_replicaset:
  #    replica_set: "{{ mongodb_replSet_name }}"
  #    login_host: "127.0.0.1"
  #    login_port: "{{ mongodb_conf_port }}"
  #    login_user: "{{ mongodb_admin_user }}"
  #    login_password: "{{ mongodb_admin_password }}"
  #    arbiter_only: "{{ mongodb_replSet_arbiter }}"
  #    members:
  #    - localhost:2223
  #    - localhost:2224

