---
- block:
  - name: initiate replica set
    community.mongodb.mongodb_replicaset:
      replica_set: "rs0"
      login_host: "127.0.0.1"
      login_port: "2224"
      login_user: "root"
      login_password: "haslo123"
      members:
      - 127.0.0.1:2223
      validate: no

