---
- block:
  - name: Initiate replica set
    community.mongodb.mongodb_replicaset:
      replica_set: "rs0"
      login_host: "centos"
      login_port: "27017"
      #      login_user: "myUserAdmin"
      #    login_password: "abc123"
      members:
      - "centos2"
      - "centos3"
      validate: no

