---
- block:
  - name: initiate replica set
    community.mongodb.mongodb_replicaset:
      state: initiated
      replset: "{{ mongodb_replSet_name }}"
      login_host: "127.0.0.1"
      login_port: "{{ mongodb_conf_port }}"
      priority: "501"
      votes: "{{ mongodb_replSet_votes }}"
      member: "{{ mongodb_replSet_member }}:{{ mongodb_conf_port }}"
    when: mongodb_replSet_isMaster

  - name: connect to master
    community.mongodb.mongodb_replicaset:
      state: present
      replset: "{{ mongodb_replSet_name }}"
      login_host: "{{ mongodb_replSet_master }}"
      login_port: "{{ mongodb_conf_port }}"
      priority: "{{ mongodb_replSet_priority | default(omit) }}"
      arbiter_only: "{{ mongodb_replSet_arbiter }}"
      votes: "{{ mongodb_replSet_votes }}"
      member: "{{ mongodb_replSet_member }}:{{ mongodb_conf_port }}"
    when: not mongodb_replSet_isMaster
  when: not mongodb_conf_auth

- block:
  - name: initiate replica set (authenticated)
    community.mongodb.mongodb_replicaset:
      state: initiated
      replset: "{{ mongodb_replSet_name }}"
      login_host: "127.0.0.1"
      login_port: "{{ mongodb_conf_port }}"
      login_user: "{{ mongodb_admin_user }}"
      login_password: "{{ mongodb_admin_password }}"
      priority: "501"
      votes: "{{ mongodb_replSet_votes }}"
      member: "{{ mongodb_replSet_member }}:{{ mongodb_conf_port }}"
    when: mongodb_replSet_isMaster

  - name: connect to master (authenticated)
    community.mongodb.mongodb_replicaset:
      state: present
      replset: "{{ mongodb_replSet_name }}"
      login_host: "{{ mongodb_replSet_master }}"
      login_port: "{{ mongodb_conf_port }}"
      login_user: "{{ mongodb_admin_user }}"
      login_password: "{{ mongodb_admin_password }}"
      priority: "{{ mongodb_replSet_priority | default(omit) }}"
      arbiter_only: "{{ mongodb_replSet_arbiter }}"
      votes: "{{ mongodb_replSet_votes }}"
      member: "{{ mongodb_replSet_member }}:{{ mongodb_conf_port }}"
    when: not mongodb_replSet_isMaster
  when: mongodb_conf_auth

