---
- name: stop mongodb instance
  service:
    name: mongod
    state: stopped

- name: "{{ 'enable' if mongodb_safeMode else 'disable' }} safeMode"
  template:
    src: mongod.conf.j2
    dest: "{{ mongodb_conf_file }}"

- name: start mongodb instance
  service:
    name: mongod
    state: started
