version: "3.9"

services:
    centos:
        command: centos --cap-add SYS_ADMIN --cap-add NET_ADMIN
        container_name: centos
        build: centos
        image: centos
        ports:
            - "2222:22"
            - "27001:27017"
        volumes:
            - /sys/fs/cgroup/:/sys/fs/cgroup:ro
        cap_add:
            - SYS_ADMIN
            - NET_ADMIN
    centos2:
        command: centos --cap-add SYS_ADMIN --cap-add NET_ADMIN
        container_name: centos2
        build: centos
        image: centos
        ports:
            - "2223:22"
            - "27002:27017"
        volumes:
            - /sys/fs/cgroup/:/sys/fs/cgroup:ro
        cap_add:
            - SYS_ADMIN
            - NET_ADMIN
    centos3:
        command: centos --cap-add SYS_ADMIN --cap-add NET_ADMIN
        container_name: centos3
        build: centos
        image: centos
        ports:
            - "2224:22"
            - "27003:27017"
        volumes:
            - /sys/fs/cgroup/:/sys/fs/cgroup:ro
        cap_add:
            - SYS_ADMIN
            - NET_ADMIN
        
networks:
    default:
        external: true
        name: my-overlay

